In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from sqlalchemy import text

#clemens access

url1 = "datafiles/df_final_demo.txt"
url2 = "datafiles/df_final_web_data_pt_1.txt"
url3 = "datafiles/df_final_web_data_pt_2.txt"
url4 = "datafiles/df_final_experiment_clients.txt"
df_final_demo = pd.read_csv(url1)
df_final_demo
df_final_web_data_pt_1 = pd.read_csv(url2)
df_final_web_data_pt_1
df_final_web_data_pt_2 = pd.read_csv(url3)
df_final_web_data_pt_2
df_final_web_data = pd.concat([df_final_web_data_pt_1, df_final_web_data_pt_2], axis=0, join='outer', ignore_index=True)
df_final_web_data
df_final_experiment_clients = pd.read_csv(url4)
df_final_experiment_clients
df_fwd_san=pd.read_csv("datafiles/df_fwd_steps_as_numbers.csv")

In [12]:
df=pd.merge(df_fwd_san, df_final_experiment_clients, on="client_id")
df=pd.merge(df,df_final_demo, on="client_id")

def addstepchange(df):
  df['prev_process_step'] = df['process_step'].shift(1)
  df['prev_visit_id'] = df['visit_id'].shift(1)
  df['step_change'] = np.where(df['visit_id'] == df['prev_visit_id'],
                                 df['process_step'] - df['prev_process_step'],
                                 np.nan)
  df = df.drop(columns=['prev_process_step', 'prev_visit_id'])
  return df

def adderrorbool(df):
  df['iserror'] = df['step_change'] < 1
  return df


df=df.sort_values(by=["client_id","visitor_id","visit_id","date_time"])

df=addstepchange(df)
df=adderrorbool(df)

,Unnamed: 0,client_id,visitor_id,visit_id,process_step,date_time,Variation,clnt_tenure_yr,clnt_tenure_mnth,clnt_age,gendr,num_accts,bal,calls_6_mnth,logons_6_mnth,step_change,iserror
280826,285515,169,201385055_71273495308,749567106_99161211863_557568,0,2017-04-12 20:19:36,NaN,21.0,262.0,47.5,M,2.0,501570.72,4.0,4.0,NaN,False
280825,285514,169,201385055_71273495308,749567106_99161211863_557568,1,2017-04-12 20:19:45,NaN,21.0,262.0,47.5,M,2.0,501570.72,4.0,4.0,1.0,False
280824,285513,169,201385055_71273495308,749567106_99161211863_557568,2,2017-04-12 20:20:31,NaN,21.0,262.0,47.5,M,2.0,501570.72,4.0,4.0,1.0,False
280823,285512,169,201385055_71273495308,749567106_99161211863_557568,3,2017-04-12 20:22:05,NaN,21.0,262.0,47.5,M,2.0,501570.72,4.0,4.0,1.0,False
280822,285511,169,201385055_71273495308,749567106_99161211863_557568,4,2017-04-12 20:23:09,NaN,21.0,262.0,47.5,M,2.0,501570.72,4.0,4.0,1.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
269918,274435,9999839,948322592_28990736246,715530422_68620416793_515645,0,2017-03-29 12:11:32,NaN,13.0,160.0,28.5,F,2.0,67425.35,3.0,3.0,0.0,True
269917,274434,9999839,948322592_28990736246,715530422_68620416793_515645,1,2017-03-29 12:11:35,NaN,13.0,160.0,28.5,F,2.0,67425.35,3.0,3.0,1.0,False
269916,274433,9999839,948322592_28990736246,715530422_68620416793_515645,2,2017-03-29 12:11:50,NaN,13.0,160.0,28.5,F,2.0,67425.35,3.0,3.0,1.0,False
269915,274432,9999839,948322592_28990736246,715530422_68620416793_515645,3,2017-03-29 12:12:28,NaN,13.0,160.0,28.5,F,2.0,67425.35,3.0,3.0,1.0,False
269914,274431,9999839,948322592_28990736246,715530422_68620416793_515645,4,2017-03-29 12:13:03,NaN,13.0,160.0,28.5,F,2.0,67425.35,3.0,3.0,1.0,False